name: "Format"

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install --frozen-lockfile
      - name: format check
        if: ${{ github.event_name == 'pull_request' }}
        uses: EPMatt/reviewdog-action-prettier@v1
        with:
          reporter: github-pr-review
          filter_mode: nofilter
          fail_on_error: "true"
      - name: format check
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          bun format
          git diff --exit-code
